version: '3.1'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '5000:80'
networks:
  default:
    external:
      name: db-net