# version: '3.2'

# services:
#    db:
#       image: mysql:8.0
#       container_name: appsDB
#       restart: always
#       ports:
#        - '6603:3306'
#       environment:
#         MYSQL_ROOT_PASSWORD: helloworld

#    app:
#       depends_on:
#        - db
#       image: phpmyadmin/phpmyadmin
#       container_name: phpmyadmin
#       restart: always
#       ports:
#        - '8080:80'
#       environment:
#         PMA_HOST: db

version: ‘3.1’
services:
  mysql:
    image: mysql:8
    command: ‘--default-authentication-plugin=mysql_native_password’
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ‘3307:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    restart: always
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ‘5000:80’
networks:
  default:
    external:
      name: db-net